# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53e95e9c7cc1e89c76db71b0ae9cb7d9d3ea901c8c9c6764dda5ec5a71a4a66924b7b6b532084001716dc2e668e1655ddd8de61495452a158ff5f7a1be4d5f30

test:
  secret_key_base: b5222da55f40b31c232b6d77e41bb887f44661dd3982ece310bdb1e637077a680ca555aa435be4ec1f0f9c46c8431d3b6d66fc28fee8e57d0f683b2eff0e1d23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
